# Generated by Django 4.1.3 on 2022-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_id', models.CharField(max_length=10, unique=True)),
                ('origin_link', models.CharField(max_length=200)),
            ],
        ),
    ]
